### PR TITLE
[FEATURE] Generate build artifact on project creation

### PR DESCRIPTION
**Pull request by eliashaeussler**
Related: CPS-IT/project-builder#12

### CODE REVIEW

**Comment by eliashaeussler** [comment]
Can be tested together with CPS-IT/project-builder#75 and merged once said PR is merged and released.

**Comment by mteu** [comment]
```
Problem 1
    - Root composer.json requires cpsit/typo3-project-template dev-feature/build-artifact -> satisfiable by cpsit/typo3-project-template[dev-feature/build-artifact].
    - cpsit/typo3-project-template dev-feature/build-artifact requires cpsit/project-builder ^1.4 -> found cpsit/project-builder[1.4.0] but these were not loaded, likely because it conflicts with another require.
```

**Comment by mteu** [comment]
For the purpose of simulation one would need to allow the current project-builder without harder requirement:
```twig
# installer/composer.json.twig

"replace": {
    "cpsit/project-builder": "*"
},
```
> ```
> Problem 1
>     - Root composer.json requires cpsit/typo3-project-template dev-feature/build-artifact -> satisfiable by cpsit/typo3-project-template[dev-feature/build-artifact].
>     - cpsit/typo3-project-template dev-feature/build-artifact requires cpsit/project-builder ^1.4 -> found cpsit/project-builder[1.4.0] but these were not loaded, likely because it conflicts with another require.
> ```

**Review by mteu — APPROVED** [review]
As mentioned in https://github.com/CPS-IT/typo3-project-template/pull/21#issuecomment-1386908412. The actual generation of the build-artefact works smoothly. Only in my edgy test scenario I've run into a composer issue. Apart from that 👍.

**Comment by mteu** [comment]
I'd say this PR is ready, approved and mergeable.

**Pull request merged**
